# Generated by Django 3.1.5 on 2021-03-19 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Juego',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, verbose_name='nombre del juego')),
                ('description', models.TextField(blank=True, verbose_name='Descripcion de la categoria')),
                ('price', models.FloatField(default=0)),
                ('image', models.URLField(blank=True)),
                ('link_url', models.URLField(blank=True)),
                ('backimage', models.URLField(blank=True)),
            ],
            options={
                'verbose_name': 'Juego',
                'verbose_name_plural': 'Juegos',
            },
        ),
    ]
